### ISSUE TITLE
Requesting help from Mac/Linux to smoke test jar file

### ISSUE THREAD

**Issue by DesSnowy** [nus-cs2103-AY2425S1/forum#414] opened 2024-09-22 16:04 UTC
Looking for help in smoke testing my IP. The user guide can be found [here](https://dessnowy.github.io/ip/), while the jar file can be found [here](https://github.com/DesSnowy/ip/releases/tag/A-Release).

Thanks in advance!

**Comment by starrdye** [comment] 2024-09-22 16:35
Works on MacOs

Tested commands: `list`, `todo`

<img width="387" alt="image" src="https://github.com/user-attachments/assets/1690fff1-edbc-42f8-bc47-ee7efd87e317">

**Comment by Quasant** [comment] 2024-09-22 16:36
Works fine for me. However, I am able to create To-Dos with empty descriptions. Also, small nit but in your user guide, the sample output for event is missing a closing parenthesis.

**Comment by yuanchengg** [comment] 2024-09-23 04:48
Works on my Mac. Everything looks great and all commands work as intended.
![image](https://github.com/user-attachments/assets/6416f94d-0047-491c-897c-3b0771b5490c)

**Comment by rimgik** [comment] 2024-09-23 04:53
Works on my mac too! Well done.
<img width="398" alt="Screenshot 2024-09-23 at 12 52 46 PM" src="https://github.com/user-attachments/assets/700f2e88-8a63-4952-8f9e-159a7ca05b94">

**Comment by zhiyi12345** [comment] 2024-09-24 10:19
Works on MacOS

I am able to call list with random string attached after `list`. Perhaps you can check for additional user input after `list`.
<img width="512" alt="Screenshot 2024-09-24 at 5 59 34 PM" src="https://github.com/user-attachments/assets/240099b0-776a-4f2a-9bb0-6b7cbc75f58c">


I am also able to create an event where its from date is after the to date. Perhaps you can add a conditional check on the from and to dates to ensure that the timing of the event is valid.
<img width="512" alt="Screenshot 2024-09-24 at 6 14 31 PM" src="https://github.com/user-attachments/assets/9173bd25-5027-45e8-88bf-bd0debb22bab">

**Closed as completed** 2024-09-25 16:36 UTC
Labels: type-HelpRequest :sos:
