### ISSUE TITLE
Requesting to help smoke test my jar file

### ISSUE THREAD

**Issue by lavanyagarg112** [nus-cs2103-AY2425S1/forum#344] opened 2024-09-19 04:56 UTC
Hi everyone, I'm a Mac user.

It would be very helpful if my jar file could be smoke tested.

Resources:
[Jar File](https://github.com/lavanyagarg112/ip/releases/tag/A-Release)
[User Guide](https://lavanyagarg112.github.io/ip/)

Thanks!

**Comment by zzzlou** [comment] 2024-09-19 05:16
Hi, I am a mac user too. It works well on my side.

**Comment by elliot-tang** [comment] 2024-09-19 05:33
Hi, I'm a Windows user, works well for me too! 

Just to check, is the `bye` command supposed to do anything? When I tried it, it showed the exit message but didn't automatically exit the application. Is closing the application window with X the only way to exit the application?

Otherwise, all other features work as intended. Great job with the UI as well! :)

**Comment by SwaminathanViswa** [comment] 2024-09-19 05:53
Hello! I am a windows user too and it works fine! 

Maybe you could provide a welcome message with the list of functions it can do because currently if I do not know what commands there are, I would not be able to do anything with the application. It helps to improve your usability!

Otherwise the code runs fine and I really like your UI too 😄

**Comment by lavanyagarg112** [comment] 2024-09-19 05:55
Thank you so much everyone! 

Regarding the bye function, no it does not automatically exit as of now

And for the commands, it can be seen by typing `help`. But thank you for the suggestion to display it when the user opens the application!

In this version of my IP, I decided to not keep `bye` as a command (which I assume is allowed?)

**Comment by choonzies** [comment] 2024-09-19 07:53
Hello! Windows user here, works fine for me too! 

On top of the previous discussions, perhaps it may be useful to add a title at the title bar of the window to facilitate the screenshot for the submission.

Pretty UI!

**Comment by lithops-zty** [comment] 2024-09-19 08:42
Hello! I've tested on Windows and I would say it's an excellent product!

One suggestion I have is to consider making your `find` command case-insensitive. This allows more flexibility and will make the command even more useful.

I really love how the dialog box changes color for different commands!

**Comment by lavanyagarg112** [comment] 2024-09-19 15:37
Thank you so much.

Regarding the `bye` command, i have made it a command now to facilitate easy exit of the programme.

Regarding the suggestion for `find` command, and title, thank you so much for these suggestions, I will try to incorporate them!

**Closed as completed** 2024-10-02 18:24 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
