### ISSUE TITLE
Ubuntu check fails TestFX

### ISSUE THREAD

**Issue by teamotitan** [nus-cs2103-AY2425S1/forum#571] opened 2024-10-24 06:37 UTC
Hello guys. I saw the AB4 code, copied and edited the code to suit our application. When I pushed it to Github, it does not pass for Ubuntu. 

![image](https://github.com/user-attachments/assets/91690385-f705-41fa-9696-be960f0064fa)

Here is the details <br>
![image](https://github.com/user-attachments/assets/6e5edef0-b5c0-40e5-b85b-656c29aa2925)

Can anyone help me?

**Comment by damithc** [comment] 2024-10-24 07:16
@teamotitan It might help to point to the PR in question so that others can see what you changed.

**Comment by teamotitan** [comment] 2024-10-24 07:52
Ahhhh I see thank you prof. Here is the link guys

https://github.com/AY2425S1-CS2103T-F14a-1/tp/pull/150

**Comment by damithc** [comment] 2024-10-24 08:00
@teamotitan While waiting for inputs from others (note that most may not even be doing GUI testing, as it is not required), you can trim down the PR to a bare minimum (i.e., one simple GUI test), and see if that works. If it works, the problem is caused by one specific test. You can find which one by adding them incrementally. But even the simplest test doesn't work, there is a flaw in the approach/infrastructure itself.

Even in AB4 we had this kind of problems with GUI testing on Linux. 

In the worst case, you can try disabling GUI tests on Ubuntu (running them on two OS'es is still better than none at all).

**Comment by teamotitan** [comment] 2024-10-24 08:11
Okay I’ll try what u suggested prof. Thank you!

**Comment by damithc** [comment] 2024-11-03 13:37
@teamotitan How did it go? Did you manage to get it working?

**Comment by teamotitan** [comment] 2024-11-03 13:40
Hahahah sorry prof we felt that we spent quite a bit of time on the testing already, and since it is optional, did not want to spend more time, thus so we stopped experimenting

**Comment by damithc** [comment] 2024-11-03 14:17
@teamotitan I see. Yes, getting GUI testing to work is hard, especially in CI. 
Anyway, let's close this issue as we don't expect any further developments on this.

**Closed as completed by damithc** 2024-11-03 14:17 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
