### ISSUE TITLE
branch-A-CodeQuality can't be detected

### ISSUE THREAD

**Issue by lancehaha** [nus-cs2103-AY2425S1/forum#286] opened 2024-09-14 09:44 UTC
<img width="987" alt="image" src="https://github.com/user-attachments/assets/7e5d0d1e-b80c-4dce-8492-cc7d52be8762">
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/34df2cbd-c08d-4eda-b9e8-1e60e908780a">
somehow the dashboard script is not detecting my branch-A-CodeQuality branch and I don't think there is any misspelling neither, by the way the tag A-CodeQuality and the branch are pushed at the same time but one of them is detected one of them is not

**Comment by RezwanAhmed123** [comment] 2024-09-14 11:25
Can you try to delete the online repository version of the branch and then push ur local repository version of the branch again? Then you can check it again later when the dashboard updates.

In the meantime maybe you can show us ur git branch graph as well so we can see if there’s any issues with the order u merged/unmerged etc.

**Comment by lancehaha** [comment] 2024-09-15 03:43
@RezwanAhmed123 
this is my branch graph i'm sorry it's a bit messy because some thing went wrong due to my local repository conflict with the remote one so took a lot of time and effort for me solve it
<img width="726" alt="image" src="https://github.com/user-attachments/assets/42be7fc7-85e5-4ff2-a00d-85803885eef8">

**Comment by damithc** [comment] 2024-09-15 04:05
@lancehaha Previously, the problem was caused by this:
![image](https://github.com/user-attachments/assets/c7d87497-531e-4842-a2c0-7a23de0da791)

For more details on this problem, you can refer to the troubleshooting tips at the top of the [iP progress dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html).

This problem seems to have been fixed now in your latest fork. So, you can wait till the next dashboard update to see if the branch is recognized by the dashboard.

![image](https://github.com/user-attachments/assets/90cd6f97-5338-4016-a2fd-a7556144e526)

**Comment by lancehaha** [comment] 2024-09-15 11:34
@damithc thank you prof working now

**Comment by damithc** [comment] 2024-09-15 12:07
@lancehaha Good to hear that 👍 
If the issue is resolved, you can close this issue now.

**Closed as completed** 2024-09-18 12:42 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
